version: '3.8'

services:

  backend:
    build:
      context: ./observatorio_api
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: observatorioserver.postgres.database.azure.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: observatorioadmin
      DB_PASSWORD: Monitorpuear2
      COSMOS_ENDPOINT: https://datos-cosmos.documents.azure.com:443/ 
      COSMOS_KEY: qiQcJSvCarkoxOemEpqvzZeA3xk2AoJIaHOSzuR0IcfsZxvAllc4BDoPsid5p1EpSeeFupt9JAPTACDbUyxgAw==
      COSMOS_DB: PUEAR
      TTN_SERVER: mqtt://nam1.cloud.thethings.network:1883
      TTN_USERNAME: puar-unl-esp32@ttn
      TTN_PASSWORD: NNSXS.FGSQU3PH2K2E32I5U5QDUFKURE4OB42PWDP6N7A.GBTQGXU4TRE3ELIOBWTBLGXDOFQPFIN5UH6CVDHU27Q2E4XMHO3Q
      TTN_TOPIC_TEMPLATE: v3/puar-unl-esp32@ttn/devices/{id}/up
      KEY_SQ: OBSERVATORIO-IOT-MQTT
      KEY: OBSERVATORIO-IOT
    volumes:
      - backend_data:/usr/src/app
    ports:
      - "3006:3006"
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
