# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - observatorioapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_SQ: ${{ secrets.KEY_SQ }}
      KEY: ${{ secrets.KEY }}
      COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
      COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
      COSMOS_DB: ${{ secrets.COSMOS_DB }}
      TTN_USERNAME: ${{ secrets.TTN_USERNAME }}
      TTN_PASSWORD: ${{ secrets.TTN_PASSWORD }}
      TTN_SERVER: ${{ secrets.TTN_SERVER }}
      TTN_TOPIC_TEMPLATE: ${{ secrets.TTN_TOPIC_TEMPLATE }}
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: observatorio_api
        run: |
          npm install
          npm start --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F07E89C550844C11981DAA9E3E08460F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA4E04C3CF0A43549D6C195ED6F73CF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3F5AFE1141040C2B0EED99B45B65866 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'observatorioapi'
          slot-name: 'Production'
          package: .
          